### ISSUE TITLE
Error: Cannot find module 'syntax-error'
Require stack:
- /storage/emulated/0/botwea-main/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/storage/emulated/0/botwea-main/main.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/storage/emulated/0/botwea-main/main.js' ]
}

### ISSUE THREAD

**Issue by MrPOKS** [Arya274/Arya-BOT3#4]

**Comment by MrPOKS** [comment]
Itu awalnya https://github.com/Arya274/Arya-BOT3

Aku ganti Arya-BOT3 = botwea-main

Waktu install
pkg install git
pkg install ffmpeg
pkg install imagemagick
pkg install nodejs
cd /sdcard
cd botwea-main
npm i
node index.js

**Comment by Miaweers** [comment]
Pindahin filenya ke $HOME dulu

**Comment by MrPOKS** [comment]
Termux

**Comment by Bintangp02** [comment]
Okh  Nanti Gue Coba semoga Work:)
